// Talent source locations (universities, colleges, job boards)
export const talentSources = [
  {
    id: "ts2",
    name: "Imperial College London",
    type: "university",
    coordinates: [51.5, -0.17] as [number, number],
    skills: [
      "Electrical Theory (Fundamentals)",
      "Energy Storage",
      "Solar Power",
    ],
    graduates: 250,
    address: "South Kensington Campus, London SW7 2AZ",
    phone: "+44 20 7589 5111",
    email: "electrical.engineering@imperial.ac.uk",
    website: "www.imperial.ac.uk",
    courses: [
      "MEng Electrical & Electronic Engineering",
      "MSc Sustainable Energy Futures",
      "MSc Energy Technology",
    ],
  },
  {
    id: "ts3",
    name: "University of Manchester",
    type: "university",
    coordinates: [53.47, -2.23] as [number, number],
    skills: ["Wind Energy", "Marine", "Electrical Theory (Fundamentals)"],
    graduates: 180,
    address: "Oxford Road, Manchester M13 9PL",
    phone: "+44 161 306 6000",
    email: "eng.admissions@manchester.ac.uk",
    website: "www.manchester.ac.uk",
    courses: [
      "BEng Renewable Energy Engineering",
      "MSc Electrical Power Systems",
      "MEng Mechanical Engineering",
    ],
  },
  {
    id: "ts4",
    name: "Cardiff University",
    type: "university",
    coordinates: [51.49, -3.18] as [number, number],
    skills: ["Solar Power", "Energy Storage", "Hazardous Voltages"],
    graduates: 95,
    address: "The Parade, Cardiff CF24 3AA",
    phone: "+44 29 2087 4000",
    email: "engineering@cardiff.ac.uk",
    website: "www.cardiff.ac.uk",
    courses: [
      "BEng Electrical & Electronic Engineering",
      "MSc Sustainable Energy & Environment",
      "MSc Electrical Energy Systems",
    ],
  },
  {
    id: "ts5",
    name: "University of Edinburgh",
    type: "university",
    coordinates: [55.94, -3.19] as [number, number],
    skills: [
      "Hydrogen Fundamentals",
      "R&D Interactive Laboratories",
      "Hydrogen Production",
    ],
    graduates: 140,
    address: "Old College, South Bridge, Edinburgh EH8 9YL",
    phone: "+44 131 650 1000",
    email: "eng.school@ed.ac.uk",
    website: "www.ed.ac.uk",
    courses: [
      "MSc Sustainable Energy Systems",
      "BEng Chemical Engineering",
      "PhD Hydrogen Energy Research",
    ],
  },
  {
    id: "ts6",
    name: "Newcastle College",
    type: "college",
    coordinates: [54.97, -1.61] as [number, number],
    skills: ["Plant & Machinery", "Hazardous Voltages", "Storage Tanks"],
    graduates: 65,
    address: "Rye Hill Campus, Scotswood Road, Newcastle NE4 7SA",
    phone: "+44 191 200 4000",
    email: "enquiries@ncl-coll.ac.uk",
    website: "www.ncl-coll.ac.uk",
    courses: [
      "HNC Electrical & Electronic Engineering",
      "Level 3 Diploma in Engineering",
      "HND Mechanical Engineering",
    ],
  },
  {
    id: "ts7",
    name: "Birmingham City University",
    type: "university",
    coordinates: [52.48, -1.89] as [number, number],
    skills: [
      "Electrical Theory (Fundamentals)",
      "Intermediate Electrical Theory",
      "Solar Power",
    ],
    graduates: 110,
    address: "Millennium Point, Curzon Street, Birmingham B4 7XG",
    phone: "+44 121 331 5000",
    email: "engineering@bcu.ac.uk",
    website: "www.bcu.ac.uk",
    courses: [
      "BEng Electrical Engineering",
      "MSc Renewable Energy Engineering",
      "BEng Electronic Engineering",
    ],
  },
  {
    id: "ts8",
    name: "Liverpool John Moores",
    type: "university",
    coordinates: [53.41, -2.98] as [number, number],
    skills: ["Marine", "Wind Energy", "Storage Tanks"],
    graduates: 85,
    address: "Byrom Street, Liverpool L3 3AF",
    phone: "+44 151 231 2121",
    email: "courses@ljmu.ac.uk",
    website: "www.ljmu.ac.uk",
    courses: [
      "BEng Maritime Engineering",
      "MSc Offshore & Ocean Technology",
      "BEng Mechanical & Marine Engineering",
    ],
  },
  {
    id: "ts9",
    name: "Leeds College of Building",
    type: "college",
    coordinates: [53.8, -1.55] as [number, number],
    skills: [
      "Hazardous Voltages",
      "Plant & Machinery",
      "Electrical Theory (Fundamentals)",
    ],
    graduates: 45,
    address: "North Street, Leeds LS2 7QT",
    phone: "+44 113 222 6000",
    email: "info@lcb.ac.uk",
    website: "www.lcb.ac.uk",
    courses: [
      "Level 3 Electrical Installation",
      "HNC Building Services Engineering",
      "Level 2 Diploma in Electrical Installations",
    ],
  },
  {
    id: "ts10",
    name: "Indeed - Glasgow",
    type: "jobboard",
    coordinates: [55.86, -4.25] as [number, number],
    skills: ["Hydrogen Fundamentals", "Electrolyser(s)", "Plant & Machinery"],
    candidates: 340,
    address: "Online Platform",
    phone: "",
    email: "support@indeed.com",
    website: "www.indeed.co.uk",
  },
  {
    id: "ts11",
    name: "LinkedIn Jobs - Bristol",
    type: "jobboard",
    coordinates: [51.45, -2.59] as [number, number],
    skills: ["Solar Power", "Energy Storage", "Wind Energy"],
    candidates: 520,
    address: "Online Platform",
    phone: "",
    email: "support@linkedin.com",
    website: "www.linkedin.com/jobs",
  },
  {
    id: "ts12",
    name: "Reed - Sheffield",
    type: "jobboard",
    coordinates: [53.38, -1.47] as [number, number],
    skills: [
      "Hazardous Voltages",
      "Electrical Theory (Fundamentals)",
      "Plant & Machinery",
    ],
    candidates: 280,
    address: "Online Platform",
    phone: "",
    email: "support@reed.co.uk",
    website: "www.reed.co.uk",
  },
  {
    id: "ts13",
    name: "Totaljobs - Nottingham",
    type: "jobboard",
    coordinates: [52.95, -1.15] as [number, number],
    skills: ["Energy Storage", "Solar Power", "Wind Energy"],
    candidates: 195,
    address: "Online Platform",
    phone: "",
    email: "support@totaljobs.com",
    website: "www.totaljobs.com",
  },
  {
    id: "ts14",
    name: "Queen's University Belfast",
    type: "university",
    coordinates: [54.58, -5.94] as [number, number],
    skills: ["Marine", "Wind Energy", "Hydrogen Fundamentals"],
    graduates: 75,
    address: "University Road, Belfast BT7 1NN",
    phone: "+44 28 9024 5133",
    email: "engineering@qub.ac.uk",
    website: "www.qub.ac.uk",
    courses: [
      "MEng Mechanical Engineering",
      "MSc Advanced Marine Engineering",
      "BEng Aerospace Engineering",
    ],
  },
];
